;;; dracula-pro-theme.el --- an Emacs 24 theme based on Dracula Pro (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1588201373
;;; Original author: Zeno Rocha
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from Dracula Pro (tmTheme) by Zeno Rocha
;;
;;; Code:

(deftheme dracula-pro
  "dracula-pro-theme - Created by tmtheme-to-deftheme - 2020-04-29 17:02:53 -0600")

(custom-theme-set-variables
 'dracula-pro
)

(custom-theme-set-faces
 'dracula-pro
 ;; basic theming.

 '(default ((t (:foreground "#f8f8f2" :background "#22212C" ))))
 '(region  ((t (:background "#454158"))))
 '(cursor  ((t (:background "#f8f8f0"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#4d4c54"  :background "#373640" ))))
 '(fringe                              ((t (                       :background "#373640" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#d6d6b2"  :background "#373640" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#f8f8f2"  :background "#373640" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-comment-face ((t (:foreground "#7970A9"  ))))
 '(font-lock-string-face ((t (:foreground "#FFFF80"  ))))
 '(font-lock-builtin-face ((t (:foreground "#9580FF"  ))))
 '(font-lock-variable-name-face ((t (  ))))
 '(font-lock-keyword-face ((t (:foreground "#FF80BF"  ))))
 '(font-lock-type-face ((t (:foreground "#80FFEA"  :underline t))))
 '(font-lock-function-name-face ((t (:foreground "#8AFF80"  ))))
 '(js3-function-param-face ((t (:foreground "#FFCA80"  :italic t))))
 '(js2-function-param ((t (:foreground "#FFCA80"  :italic t))))
 '(font-lock-warning-face ((t (:foreground "#F8F8F0" :background "#9580FF" ))))
 '(diff-removed ((t (:foreground "#FF80BF"  ))))
 '(diff-added ((t (:foreground "#8AFF80"  ))))
 '(diff-changed ((t (:foreground "#E6DB74"  ))))
 '(markdown-list-face ((t (:foreground "#FF80BF"  ))))
 '(markdown-blockquote-face ((t (:foreground "#7970A9" :background "#7970A9" :italic t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#7970A9"  ))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#554f77"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#5d5783"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#665f8f"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#6f689a"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#7a74a2"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#8580aa"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#918cb2"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#9c98ba"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#a8a3c2"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'dracula-pro)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; dracula-pro-theme.el ends here
